language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
before_install:
  - gem install bundler -v"~>1.17"

