language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
gemfile:
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_6.1.gemfile
  - gemfiles/rails_7.0.gemfile
jobs:
  exclude:
    - rvm: 2.4
      gemfile: gemfiles/rails_6.0.gemfile
before_install:
  - gem install bundler -v"~>1.17"

